name: network_calculator
description: A modern network calculator app with NetEase Cloud Music style UI
publish_to: 'none'
version: 1.6.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  file_picker: ^10.3.8
  path_provider: ^2.1.2
  material_symbols_icons: ^4.2892.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  package_info_plus: ^9.0.0
  path_provider_windows: ^2.3.0
  shared_preferences_windows: ^2.4.1
  url_launcher_windows: ^3.1.5
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter 配置
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/app-icons/
    - assets/images/icons/social-icons/
    - assets/images/icons/country-flags/
    - assets/images/icons/country-flags/flagpedia.asia/
    - assets/images/icons/country-flags/flagpedia.asia/cn.svg
    - assets/images/icons/country-flags/flagpedia.asia/tw.svg
    - assets/images/icons/country-flags/flagpedia.asia/us.svg
    - assets/images/icons/country-flags/flagpedia.asia/jp.svg
    - assets/images/icons/country-flags/flagpedia.asia/eu.svg
    - assets/fonts/

  fonts:
    - family: OPPOSans
      fonts:
        - asset: assets/fonts/OPPOSans4.0.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/OPPOSans4.0.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/OPPOSans4.0.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/OPPOSans4.0.ttf
          weight: 700
          style: normal

# Web 配置 - 放在 flutter 配置同级
web:
  # 使用 canvaskit 渲染器以获得更好的字体渲染质量
  renderer: canvaskit
  csp:
    "script-src":
      - "'self'"
      - "'unsafe-inline'"
      - "'unsafe-eval'"
    "style-src":
      - "'self'"
      - "'unsafe-inline'"
